name: Auto-Update Wiki Links

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  update-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Wiki
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki.git
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install Dependencies
        run: pip install requests markdown
      
      - name: Run Update Script
        run: python update_wiki_links.py
