name: Update Wiki

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # If your script requires additional packages, list them here

      - name: Run Wiki Update Script
        env:
          GITHUB_TOKEN: ${{ secrets.SOPHIA_TOKEN }}
        run: |
          python path/to/your_script.py
